### ISSUE TITLE
Help with Plugin

### ISSUE THREAD

**Issue by Frostist** [Siyavula/siyavula-moodle-filter#66]
Hi guys

Do I need API access for this plugin to work? My Siyavula account credentials are not allowing the plugin to work.

Thanks

**Comment by marknewlyn** [comment]
Hi @Frostist 

That's correct, credentials for the API are completely different to the regular Siyavula credentials. Please contact me on mark@siyavula.com about credentials.

A proper API page is in the works for the site.

Cheers

Mark
